version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          store_artifacts: true
          record: true
          
